
                <section>
                    <header>
                        <h1>Presentation</h1>
                    </header>

                    <p>
                        Fightly is a Game Engine for browser games, using only Open Web technologies
                        such as HTML5, CSS3 or JavaScript. It is dedicated to strategic, turn-based games
                        but could be used for any kind of Web game. As it is a free and open project, anyone
                        can extend it and add new functionnalities.
                    </p>
                </section>

                <section>
                    <header>
                        <h1>Tools</h1>
                    </header>

                    <p>
                        Fightly is based on many other Open Source projects.
                        We use Node.js server-side, and so many great modules for Node.
                        We also use Crafty.js on the client-side to handle the display and events.
                    </p>
                </section>

                <section>
                    <header>
                        <h1>How to use?</h1>
                    </header>

                    <p>
                        Fightly is not ready to use yet. We are currently developing it,
                        and hope to release a first useable version as soon as posible.
                        We also aim at creating a browser game, originally called Fightly,
                        that will demonstrate the power of the Fightly Game Engine.
                    </p>
                    <!--p>
                        Be the first to hear about Fightly's release: <strong>subscribe to our newsletter</strong>!
                    </p>
                    <form method="post" action="subscribe.php">
                        <input type="email" name="newsletter_email" />
                        <button type="submit">Subscribe</button>
                    </form-->
                </section>
